name: GraalVM Native Image builds
on: workflow_dispatch
jobs:
  build:
    name: Tic Tac Toe on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    defaults:
      run:
        working-directory: ./v18
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build Network.java for Linux/MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          javac -cp +libs/jgroups-5.0.0.Final.jar -sourcepath . Network.java
          native-image -cp ".:+libs/*" --report-unsupported-elements-at-runtime Network
      
      - name: Build Network.java for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          javac -cp +libs/jgroups-5.0.0.Final.jar -sourcepath . Network.java
          native-image -cp ".;+libs/*" --report-unsupported-elements-at-runtime Network
      
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: TicTacToe-${{ matrix.os }}
          path: /v18/network
